module.exports = {
  userFormateError:{
    code:1001,
    message:"用户名或密码不能为空",
    result:null
  },
  userAlreadyExited:{
    code:1002,
    message:"用户已存在",
    result:null
  },
  regiesterError:{
    code:1002,
    message:"用户注册错误",
    result:null
  },
  userNotExited:{
    code:1004,
    message:"用户不存在",
    result:null
  },
  userLoginError:{
    code:1005,
    message:"登录失败",
    result:null
  },
  userPasswordError:{
    code:1006,
    message:"密码不正确",
    result:null
  },
  tokenExpiredError:{
    code:1010,
    message:"token已过期",
    result:null
  },
  invalidToken:{
    code:1011,
    message:"无效的token",
    result:null
  }
}
